#!/bin/bash

read -p "Enter first number: " a
read -p "Enter second number: " b

sum1=$((a + b))
echo "Sum using (( )) is: $sum1"

sum2=`expr $a + $b`
echo "Sum using expr is: $sum2"





#!/bin/bash

read -p "Enter first number: " a
read -p "Enter second number: " b

sub1=$((a - b))
echo $sub1

sub2=`expr $a - $b`
echo $sub2







#!/bin/bash

read -p "Enter first number: " a
read -p "Enter second number: " b

mul1=$((a * b))
echo $mul1

mul2=`expr $a \* $b`
echo $mul2





#!/bin/bash

read -p "Enter first number: " a
read -p "Enter second number: " b

div=$((a / b))
echo $div



