#!/bin/bash

echo "Enter three numbers:"
read a
read b
read c

if [ $a -gt $b ]
then
  if [ $a -gt $c ]
  then
    echo "Largest is $a"
  else
    echo "Largest is $c"
  fi
else
  if [ $b -gt $c ]
  then
    echo "Largest is $b"
  else
    echo "Largest is $c"
  fi
